### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by H-gorji** [h-haghpanah/mikrotik_traffic_counter_en#7]
i see this error after installing 

ExecStart=/etc/mikrotik_traffic_counter_en/mikrotik_venv/bin/python3 analysis.py (code=exited, status=1/FAILURE)

**Comment by H-gorji** [comment]
Traceback (most recent call last):
  File "analysis.py", line 2, in <module>
    import fetch
  File "/etc/mikrotik_traffic_counter_en/analysis/fetch.py", line 1, in <module>
    import requests
i can't finding requests file

**Comment by h-haghpanah** [comment]
Hello
you can fix these issues by installing requirements.txt in root of project:
if you dont know how to install python requirements use following command :
pip install -r requirements.txt

**Comment by jult** [comment]
pip is not a workable solution for debian based systems..

**Comment by tomaskovacik** [comment]
search the required module on https://pypi.org/search/

then 

python3 -m venv /etc/mikrotik_traffic_counter_en/mikrotik_venv
source /etc/mikrotik_traffic_counter_en/mikrotik_venv/bin/activate
pip3 install NAME_OF_MODULE

restart web app
